name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm install
          cd server && npm install
          cd ..

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Create env file
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "NODE_ENV=production" >> .env

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create and navigate to app directory if it doesn't exist
            mkdir -p ~/app
            cd ~/app

            # Initialize git if not already initialized
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/sachinoo73/aahatimesheet.git
            fi
            
            # Backup current version if exists
            if [ -f package.json ]; then
              timestamp=$(date +%Y%m%d_%H%M%S)
              mkdir -p ~/backups
              cp -r . ~/backups/backup_$timestamp
            fi
            
            # Fetch and reset to match remote state
            git fetch origin main
            git reset --hard origin/main
            
            # Install dependencies
            npm install
            cd server && npm install
            cd ..
            
            # Copy env file
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
            echo "NODE_ENV=production" >> .env
            
            # Build the application
            npm run build
            
            # Start the backend server with PM2
            cd server
            pm2 restart timesheet-backend || pm2 start server.js --name "timesheet-backend"
            cd ..
            
            # Install nginx if not installed
            if ! command -v nginx &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y nginx
            fi

            # Install certbot if not installed
            if ! command -v certbot &> /dev/null; then
              sudo apt-get install -y certbot python3-certbot-nginx
            fi

            # Copy nginx configuration
            sudo cp nginx.conf /etc/nginx/sites-available/timesheet
            sudo ln -sf /etc/nginx/sites-available/timesheet /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default

            # Get SSL certificate if not exists
            if [ ! -d "/etc/letsencrypt/live/ec2-18-225-55-218.us-east-2.compute.amazonaws.com" ]; then
              sudo certbot --nginx -d ec2-18-225-55-218.us-east-2.compute.amazonaws.com --non-interactive --agree-tos -m sachinkarki2050@gmail.com
            fi

            # Start the backend with PM2
            cd server
            pm2 restart timesheet-backend || pm2 start server.js --name "timesheet-backend"
            cd ..

            # Save PM2 process list
            pm2 save

            # Verify backend is running
            if ! pm2 show timesheet-backend > /dev/null 2>&1; then
              echo "Backend failed to start - rolling back"
              cp -r ~/backups/backup_$timestamp/* .
              cd server
              pm2 restart timesheet-backend
              exit 1
            fi

            # Test nginx configuration
            sudo nginx -t

            # Restart nginx
            sudo systemctl restart nginx
            
            echo "Both services started successfully!"
            
            # Cleanup old backups (keep last 5)
            cd ~/backups && ls -t | tail -n +6 | xargs -I {} rm -rf {}
            
            echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Deployment failed!"
          # Add notification logic here (e.g., Slack, email)
